
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GalleryPhoto` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GalleryPhoto
 * 
 */
export type GalleryPhotoModel = runtime.Types.Result.DefaultSelection<Prisma.$GalleryPhotoPayload>

export type AggregateGalleryPhoto = {
  _count: GalleryPhotoCountAggregateOutputType | null
  _avg: GalleryPhotoAvgAggregateOutputType | null
  _sum: GalleryPhotoSumAggregateOutputType | null
  _min: GalleryPhotoMinAggregateOutputType | null
  _max: GalleryPhotoMaxAggregateOutputType | null
}

export type GalleryPhotoAvgAggregateOutputType = {
  order: number | null
}

export type GalleryPhotoSumAggregateOutputType = {
  order: number | null
}

export type GalleryPhotoMinAggregateOutputType = {
  id: string | null
  galleryId: string | null
  photoId: string | null
  order: number | null
  addedAt: Date | null
}

export type GalleryPhotoMaxAggregateOutputType = {
  id: string | null
  galleryId: string | null
  photoId: string | null
  order: number | null
  addedAt: Date | null
}

export type GalleryPhotoCountAggregateOutputType = {
  id: number
  galleryId: number
  photoId: number
  order: number
  addedAt: number
  _all: number
}


export type GalleryPhotoAvgAggregateInputType = {
  order?: true
}

export type GalleryPhotoSumAggregateInputType = {
  order?: true
}

export type GalleryPhotoMinAggregateInputType = {
  id?: true
  galleryId?: true
  photoId?: true
  order?: true
  addedAt?: true
}

export type GalleryPhotoMaxAggregateInputType = {
  id?: true
  galleryId?: true
  photoId?: true
  order?: true
  addedAt?: true
}

export type GalleryPhotoCountAggregateInputType = {
  id?: true
  galleryId?: true
  photoId?: true
  order?: true
  addedAt?: true
  _all?: true
}

export type GalleryPhotoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GalleryPhoto to aggregate.
   */
  where?: Prisma.GalleryPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPhotos to fetch.
   */
  orderBy?: Prisma.GalleryPhotoOrderByWithRelationInput | Prisma.GalleryPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GalleryPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPhotos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GalleryPhotos
  **/
  _count?: true | GalleryPhotoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GalleryPhotoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GalleryPhotoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GalleryPhotoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GalleryPhotoMaxAggregateInputType
}

export type GetGalleryPhotoAggregateType<T extends GalleryPhotoAggregateArgs> = {
      [P in keyof T & keyof AggregateGalleryPhoto]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGalleryPhoto[P]>
    : Prisma.GetScalarType<T[P], AggregateGalleryPhoto[P]>
}




export type GalleryPhotoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GalleryPhotoWhereInput
  orderBy?: Prisma.GalleryPhotoOrderByWithAggregationInput | Prisma.GalleryPhotoOrderByWithAggregationInput[]
  by: Prisma.GalleryPhotoScalarFieldEnum[] | Prisma.GalleryPhotoScalarFieldEnum
  having?: Prisma.GalleryPhotoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GalleryPhotoCountAggregateInputType | true
  _avg?: GalleryPhotoAvgAggregateInputType
  _sum?: GalleryPhotoSumAggregateInputType
  _min?: GalleryPhotoMinAggregateInputType
  _max?: GalleryPhotoMaxAggregateInputType
}

export type GalleryPhotoGroupByOutputType = {
  id: string
  galleryId: string
  photoId: string
  order: number
  addedAt: Date
  _count: GalleryPhotoCountAggregateOutputType | null
  _avg: GalleryPhotoAvgAggregateOutputType | null
  _sum: GalleryPhotoSumAggregateOutputType | null
  _min: GalleryPhotoMinAggregateOutputType | null
  _max: GalleryPhotoMaxAggregateOutputType | null
}

type GetGalleryPhotoGroupByPayload<T extends GalleryPhotoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GalleryPhotoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GalleryPhotoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GalleryPhotoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GalleryPhotoGroupByOutputType[P]>
      }
    >
  >



export type GalleryPhotoWhereInput = {
  AND?: Prisma.GalleryPhotoWhereInput | Prisma.GalleryPhotoWhereInput[]
  OR?: Prisma.GalleryPhotoWhereInput[]
  NOT?: Prisma.GalleryPhotoWhereInput | Prisma.GalleryPhotoWhereInput[]
  id?: Prisma.StringFilter<"GalleryPhoto"> | string
  galleryId?: Prisma.StringFilter<"GalleryPhoto"> | string
  photoId?: Prisma.StringFilter<"GalleryPhoto"> | string
  order?: Prisma.IntFilter<"GalleryPhoto"> | number
  addedAt?: Prisma.DateTimeFilter<"GalleryPhoto"> | Date | string
  gallery?: Prisma.XOR<Prisma.GalleryScalarRelationFilter, Prisma.GalleryWhereInput>
  photo?: Prisma.XOR<Prisma.PhotoScalarRelationFilter, Prisma.PhotoWhereInput>
}

export type GalleryPhotoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  galleryId?: Prisma.SortOrder
  photoId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  gallery?: Prisma.GalleryOrderByWithRelationInput
  photo?: Prisma.PhotoOrderByWithRelationInput
}

export type GalleryPhotoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  galleryId_photoId?: Prisma.GalleryPhotoGalleryIdPhotoIdCompoundUniqueInput
  AND?: Prisma.GalleryPhotoWhereInput | Prisma.GalleryPhotoWhereInput[]
  OR?: Prisma.GalleryPhotoWhereInput[]
  NOT?: Prisma.GalleryPhotoWhereInput | Prisma.GalleryPhotoWhereInput[]
  galleryId?: Prisma.StringFilter<"GalleryPhoto"> | string
  photoId?: Prisma.StringFilter<"GalleryPhoto"> | string
  order?: Prisma.IntFilter<"GalleryPhoto"> | number
  addedAt?: Prisma.DateTimeFilter<"GalleryPhoto"> | Date | string
  gallery?: Prisma.XOR<Prisma.GalleryScalarRelationFilter, Prisma.GalleryWhereInput>
  photo?: Prisma.XOR<Prisma.PhotoScalarRelationFilter, Prisma.PhotoWhereInput>
}, "id" | "galleryId_photoId">

export type GalleryPhotoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  galleryId?: Prisma.SortOrder
  photoId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  _count?: Prisma.GalleryPhotoCountOrderByAggregateInput
  _avg?: Prisma.GalleryPhotoAvgOrderByAggregateInput
  _max?: Prisma.GalleryPhotoMaxOrderByAggregateInput
  _min?: Prisma.GalleryPhotoMinOrderByAggregateInput
  _sum?: Prisma.GalleryPhotoSumOrderByAggregateInput
}

export type GalleryPhotoScalarWhereWithAggregatesInput = {
  AND?: Prisma.GalleryPhotoScalarWhereWithAggregatesInput | Prisma.GalleryPhotoScalarWhereWithAggregatesInput[]
  OR?: Prisma.GalleryPhotoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GalleryPhotoScalarWhereWithAggregatesInput | Prisma.GalleryPhotoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GalleryPhoto"> | string
  galleryId?: Prisma.StringWithAggregatesFilter<"GalleryPhoto"> | string
  photoId?: Prisma.StringWithAggregatesFilter<"GalleryPhoto"> | string
  order?: Prisma.IntWithAggregatesFilter<"GalleryPhoto"> | number
  addedAt?: Prisma.DateTimeWithAggregatesFilter<"GalleryPhoto"> | Date | string
}

export type GalleryPhotoCreateInput = {
  id?: string
  order?: number
  addedAt?: Date | string
  gallery: Prisma.GalleryCreateNestedOneWithoutPhotosInput
  photo: Prisma.PhotoCreateNestedOneWithoutGalleryPhotosInput
}

export type GalleryPhotoUncheckedCreateInput = {
  id?: string
  galleryId: string
  photoId: string
  order?: number
  addedAt?: Date | string
}

export type GalleryPhotoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gallery?: Prisma.GalleryUpdateOneRequiredWithoutPhotosNestedInput
  photo?: Prisma.PhotoUpdateOneRequiredWithoutGalleryPhotosNestedInput
}

export type GalleryPhotoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  galleryId?: Prisma.StringFieldUpdateOperationsInput | string
  photoId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPhotoCreateManyInput = {
  id?: string
  galleryId: string
  photoId: string
  order?: number
  addedAt?: Date | string
}

export type GalleryPhotoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPhotoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  galleryId?: Prisma.StringFieldUpdateOperationsInput | string
  photoId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPhotoListRelationFilter = {
  every?: Prisma.GalleryPhotoWhereInput
  some?: Prisma.GalleryPhotoWhereInput
  none?: Prisma.GalleryPhotoWhereInput
}

export type GalleryPhotoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GalleryPhotoGalleryIdPhotoIdCompoundUniqueInput = {
  galleryId: string
  photoId: string
}

export type GalleryPhotoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  galleryId?: Prisma.SortOrder
  photoId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
}

export type GalleryPhotoAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type GalleryPhotoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  galleryId?: Prisma.SortOrder
  photoId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
}

export type GalleryPhotoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  galleryId?: Prisma.SortOrder
  photoId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
}

export type GalleryPhotoSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type GalleryPhotoCreateNestedManyWithoutPhotoInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput> | Prisma.GalleryPhotoCreateWithoutPhotoInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput | Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput[]
  createMany?: Prisma.GalleryPhotoCreateManyPhotoInputEnvelope
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
}

export type GalleryPhotoUncheckedCreateNestedManyWithoutPhotoInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput> | Prisma.GalleryPhotoCreateWithoutPhotoInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput | Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput[]
  createMany?: Prisma.GalleryPhotoCreateManyPhotoInputEnvelope
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
}

export type GalleryPhotoUpdateManyWithoutPhotoNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput> | Prisma.GalleryPhotoCreateWithoutPhotoInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput | Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput[]
  upsert?: Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutPhotoInput | Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutPhotoInput[]
  createMany?: Prisma.GalleryPhotoCreateManyPhotoInputEnvelope
  set?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  disconnect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  delete?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  update?: Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutPhotoInput | Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutPhotoInput[]
  updateMany?: Prisma.GalleryPhotoUpdateManyWithWhereWithoutPhotoInput | Prisma.GalleryPhotoUpdateManyWithWhereWithoutPhotoInput[]
  deleteMany?: Prisma.GalleryPhotoScalarWhereInput | Prisma.GalleryPhotoScalarWhereInput[]
}

export type GalleryPhotoUncheckedUpdateManyWithoutPhotoNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput> | Prisma.GalleryPhotoCreateWithoutPhotoInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput | Prisma.GalleryPhotoCreateOrConnectWithoutPhotoInput[]
  upsert?: Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutPhotoInput | Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutPhotoInput[]
  createMany?: Prisma.GalleryPhotoCreateManyPhotoInputEnvelope
  set?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  disconnect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  delete?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  update?: Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutPhotoInput | Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutPhotoInput[]
  updateMany?: Prisma.GalleryPhotoUpdateManyWithWhereWithoutPhotoInput | Prisma.GalleryPhotoUpdateManyWithWhereWithoutPhotoInput[]
  deleteMany?: Prisma.GalleryPhotoScalarWhereInput | Prisma.GalleryPhotoScalarWhereInput[]
}

export type GalleryPhotoCreateNestedManyWithoutGalleryInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput> | Prisma.GalleryPhotoCreateWithoutGalleryInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput | Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput[]
  createMany?: Prisma.GalleryPhotoCreateManyGalleryInputEnvelope
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
}

export type GalleryPhotoUncheckedCreateNestedManyWithoutGalleryInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput> | Prisma.GalleryPhotoCreateWithoutGalleryInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput | Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput[]
  createMany?: Prisma.GalleryPhotoCreateManyGalleryInputEnvelope
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
}

export type GalleryPhotoUpdateManyWithoutGalleryNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput> | Prisma.GalleryPhotoCreateWithoutGalleryInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput | Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput[]
  upsert?: Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutGalleryInput | Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutGalleryInput[]
  createMany?: Prisma.GalleryPhotoCreateManyGalleryInputEnvelope
  set?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  disconnect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  delete?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  update?: Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutGalleryInput | Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutGalleryInput[]
  updateMany?: Prisma.GalleryPhotoUpdateManyWithWhereWithoutGalleryInput | Prisma.GalleryPhotoUpdateManyWithWhereWithoutGalleryInput[]
  deleteMany?: Prisma.GalleryPhotoScalarWhereInput | Prisma.GalleryPhotoScalarWhereInput[]
}

export type GalleryPhotoUncheckedUpdateManyWithoutGalleryNestedInput = {
  create?: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput> | Prisma.GalleryPhotoCreateWithoutGalleryInput[] | Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput[]
  connectOrCreate?: Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput | Prisma.GalleryPhotoCreateOrConnectWithoutGalleryInput[]
  upsert?: Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutGalleryInput | Prisma.GalleryPhotoUpsertWithWhereUniqueWithoutGalleryInput[]
  createMany?: Prisma.GalleryPhotoCreateManyGalleryInputEnvelope
  set?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  disconnect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  delete?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  connect?: Prisma.GalleryPhotoWhereUniqueInput | Prisma.GalleryPhotoWhereUniqueInput[]
  update?: Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutGalleryInput | Prisma.GalleryPhotoUpdateWithWhereUniqueWithoutGalleryInput[]
  updateMany?: Prisma.GalleryPhotoUpdateManyWithWhereWithoutGalleryInput | Prisma.GalleryPhotoUpdateManyWithWhereWithoutGalleryInput[]
  deleteMany?: Prisma.GalleryPhotoScalarWhereInput | Prisma.GalleryPhotoScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type GalleryPhotoCreateWithoutPhotoInput = {
  id?: string
  order?: number
  addedAt?: Date | string
  gallery: Prisma.GalleryCreateNestedOneWithoutPhotosInput
}

export type GalleryPhotoUncheckedCreateWithoutPhotoInput = {
  id?: string
  galleryId: string
  order?: number
  addedAt?: Date | string
}

export type GalleryPhotoCreateOrConnectWithoutPhotoInput = {
  where: Prisma.GalleryPhotoWhereUniqueInput
  create: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput>
}

export type GalleryPhotoCreateManyPhotoInputEnvelope = {
  data: Prisma.GalleryPhotoCreateManyPhotoInput | Prisma.GalleryPhotoCreateManyPhotoInput[]
  skipDuplicates?: boolean
}

export type GalleryPhotoUpsertWithWhereUniqueWithoutPhotoInput = {
  where: Prisma.GalleryPhotoWhereUniqueInput
  update: Prisma.XOR<Prisma.GalleryPhotoUpdateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedUpdateWithoutPhotoInput>
  create: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedCreateWithoutPhotoInput>
}

export type GalleryPhotoUpdateWithWhereUniqueWithoutPhotoInput = {
  where: Prisma.GalleryPhotoWhereUniqueInput
  data: Prisma.XOR<Prisma.GalleryPhotoUpdateWithoutPhotoInput, Prisma.GalleryPhotoUncheckedUpdateWithoutPhotoInput>
}

export type GalleryPhotoUpdateManyWithWhereWithoutPhotoInput = {
  where: Prisma.GalleryPhotoScalarWhereInput
  data: Prisma.XOR<Prisma.GalleryPhotoUpdateManyMutationInput, Prisma.GalleryPhotoUncheckedUpdateManyWithoutPhotoInput>
}

export type GalleryPhotoScalarWhereInput = {
  AND?: Prisma.GalleryPhotoScalarWhereInput | Prisma.GalleryPhotoScalarWhereInput[]
  OR?: Prisma.GalleryPhotoScalarWhereInput[]
  NOT?: Prisma.GalleryPhotoScalarWhereInput | Prisma.GalleryPhotoScalarWhereInput[]
  id?: Prisma.StringFilter<"GalleryPhoto"> | string
  galleryId?: Prisma.StringFilter<"GalleryPhoto"> | string
  photoId?: Prisma.StringFilter<"GalleryPhoto"> | string
  order?: Prisma.IntFilter<"GalleryPhoto"> | number
  addedAt?: Prisma.DateTimeFilter<"GalleryPhoto"> | Date | string
}

export type GalleryPhotoCreateWithoutGalleryInput = {
  id?: string
  order?: number
  addedAt?: Date | string
  photo: Prisma.PhotoCreateNestedOneWithoutGalleryPhotosInput
}

export type GalleryPhotoUncheckedCreateWithoutGalleryInput = {
  id?: string
  photoId: string
  order?: number
  addedAt?: Date | string
}

export type GalleryPhotoCreateOrConnectWithoutGalleryInput = {
  where: Prisma.GalleryPhotoWhereUniqueInput
  create: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput>
}

export type GalleryPhotoCreateManyGalleryInputEnvelope = {
  data: Prisma.GalleryPhotoCreateManyGalleryInput | Prisma.GalleryPhotoCreateManyGalleryInput[]
  skipDuplicates?: boolean
}

export type GalleryPhotoUpsertWithWhereUniqueWithoutGalleryInput = {
  where: Prisma.GalleryPhotoWhereUniqueInput
  update: Prisma.XOR<Prisma.GalleryPhotoUpdateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedUpdateWithoutGalleryInput>
  create: Prisma.XOR<Prisma.GalleryPhotoCreateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedCreateWithoutGalleryInput>
}

export type GalleryPhotoUpdateWithWhereUniqueWithoutGalleryInput = {
  where: Prisma.GalleryPhotoWhereUniqueInput
  data: Prisma.XOR<Prisma.GalleryPhotoUpdateWithoutGalleryInput, Prisma.GalleryPhotoUncheckedUpdateWithoutGalleryInput>
}

export type GalleryPhotoUpdateManyWithWhereWithoutGalleryInput = {
  where: Prisma.GalleryPhotoScalarWhereInput
  data: Prisma.XOR<Prisma.GalleryPhotoUpdateManyMutationInput, Prisma.GalleryPhotoUncheckedUpdateManyWithoutGalleryInput>
}

export type GalleryPhotoCreateManyPhotoInput = {
  id?: string
  galleryId: string
  order?: number
  addedAt?: Date | string
}

export type GalleryPhotoUpdateWithoutPhotoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gallery?: Prisma.GalleryUpdateOneRequiredWithoutPhotosNestedInput
}

export type GalleryPhotoUncheckedUpdateWithoutPhotoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  galleryId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPhotoUncheckedUpdateManyWithoutPhotoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  galleryId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPhotoCreateManyGalleryInput = {
  id?: string
  photoId: string
  order?: number
  addedAt?: Date | string
}

export type GalleryPhotoUpdateWithoutGalleryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  photo?: Prisma.PhotoUpdateOneRequiredWithoutGalleryPhotosNestedInput
}

export type GalleryPhotoUncheckedUpdateWithoutGalleryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  photoId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GalleryPhotoUncheckedUpdateManyWithoutGalleryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  photoId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GalleryPhotoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  galleryId?: boolean
  photoId?: boolean
  order?: boolean
  addedAt?: boolean
  gallery?: boolean | Prisma.GalleryDefaultArgs<ExtArgs>
  photo?: boolean | Prisma.PhotoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["galleryPhoto"]>

export type GalleryPhotoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  galleryId?: boolean
  photoId?: boolean
  order?: boolean
  addedAt?: boolean
  gallery?: boolean | Prisma.GalleryDefaultArgs<ExtArgs>
  photo?: boolean | Prisma.PhotoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["galleryPhoto"]>

export type GalleryPhotoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  galleryId?: boolean
  photoId?: boolean
  order?: boolean
  addedAt?: boolean
  gallery?: boolean | Prisma.GalleryDefaultArgs<ExtArgs>
  photo?: boolean | Prisma.PhotoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["galleryPhoto"]>

export type GalleryPhotoSelectScalar = {
  id?: boolean
  galleryId?: boolean
  photoId?: boolean
  order?: boolean
  addedAt?: boolean
}

export type GalleryPhotoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "galleryId" | "photoId" | "order" | "addedAt", ExtArgs["result"]["galleryPhoto"]>
export type GalleryPhotoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gallery?: boolean | Prisma.GalleryDefaultArgs<ExtArgs>
  photo?: boolean | Prisma.PhotoDefaultArgs<ExtArgs>
}
export type GalleryPhotoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gallery?: boolean | Prisma.GalleryDefaultArgs<ExtArgs>
  photo?: boolean | Prisma.PhotoDefaultArgs<ExtArgs>
}
export type GalleryPhotoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  gallery?: boolean | Prisma.GalleryDefaultArgs<ExtArgs>
  photo?: boolean | Prisma.PhotoDefaultArgs<ExtArgs>
}

export type $GalleryPhotoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GalleryPhoto"
  objects: {
    gallery: Prisma.$GalleryPayload<ExtArgs>
    photo: Prisma.$PhotoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    galleryId: string
    photoId: string
    order: number
    addedAt: Date
  }, ExtArgs["result"]["galleryPhoto"]>
  composites: {}
}

export type GalleryPhotoGetPayload<S extends boolean | null | undefined | GalleryPhotoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload, S>

export type GalleryPhotoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GalleryPhotoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GalleryPhotoCountAggregateInputType | true
  }

export interface GalleryPhotoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GalleryPhoto'], meta: { name: 'GalleryPhoto' } }
  /**
   * Find zero or one GalleryPhoto that matches the filter.
   * @param {GalleryPhotoFindUniqueArgs} args - Arguments to find a GalleryPhoto
   * @example
   * // Get one GalleryPhoto
   * const galleryPhoto = await prisma.galleryPhoto.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GalleryPhotoFindUniqueArgs>(args: Prisma.SelectSubset<T, GalleryPhotoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GalleryPhoto that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GalleryPhotoFindUniqueOrThrowArgs} args - Arguments to find a GalleryPhoto
   * @example
   * // Get one GalleryPhoto
   * const galleryPhoto = await prisma.galleryPhoto.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GalleryPhotoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GalleryPhotoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GalleryPhoto that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPhotoFindFirstArgs} args - Arguments to find a GalleryPhoto
   * @example
   * // Get one GalleryPhoto
   * const galleryPhoto = await prisma.galleryPhoto.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GalleryPhotoFindFirstArgs>(args?: Prisma.SelectSubset<T, GalleryPhotoFindFirstArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GalleryPhoto that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPhotoFindFirstOrThrowArgs} args - Arguments to find a GalleryPhoto
   * @example
   * // Get one GalleryPhoto
   * const galleryPhoto = await prisma.galleryPhoto.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GalleryPhotoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GalleryPhotoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GalleryPhotos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPhotoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GalleryPhotos
   * const galleryPhotos = await prisma.galleryPhoto.findMany()
   * 
   * // Get first 10 GalleryPhotos
   * const galleryPhotos = await prisma.galleryPhoto.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const galleryPhotoWithIdOnly = await prisma.galleryPhoto.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GalleryPhotoFindManyArgs>(args?: Prisma.SelectSubset<T, GalleryPhotoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GalleryPhoto.
   * @param {GalleryPhotoCreateArgs} args - Arguments to create a GalleryPhoto.
   * @example
   * // Create one GalleryPhoto
   * const GalleryPhoto = await prisma.galleryPhoto.create({
   *   data: {
   *     // ... data to create a GalleryPhoto
   *   }
   * })
   * 
   */
  create<T extends GalleryPhotoCreateArgs>(args: Prisma.SelectSubset<T, GalleryPhotoCreateArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GalleryPhotos.
   * @param {GalleryPhotoCreateManyArgs} args - Arguments to create many GalleryPhotos.
   * @example
   * // Create many GalleryPhotos
   * const galleryPhoto = await prisma.galleryPhoto.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GalleryPhotoCreateManyArgs>(args?: Prisma.SelectSubset<T, GalleryPhotoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GalleryPhotos and returns the data saved in the database.
   * @param {GalleryPhotoCreateManyAndReturnArgs} args - Arguments to create many GalleryPhotos.
   * @example
   * // Create many GalleryPhotos
   * const galleryPhoto = await prisma.galleryPhoto.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GalleryPhotos and only return the `id`
   * const galleryPhotoWithIdOnly = await prisma.galleryPhoto.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GalleryPhotoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GalleryPhotoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GalleryPhoto.
   * @param {GalleryPhotoDeleteArgs} args - Arguments to delete one GalleryPhoto.
   * @example
   * // Delete one GalleryPhoto
   * const GalleryPhoto = await prisma.galleryPhoto.delete({
   *   where: {
   *     // ... filter to delete one GalleryPhoto
   *   }
   * })
   * 
   */
  delete<T extends GalleryPhotoDeleteArgs>(args: Prisma.SelectSubset<T, GalleryPhotoDeleteArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GalleryPhoto.
   * @param {GalleryPhotoUpdateArgs} args - Arguments to update one GalleryPhoto.
   * @example
   * // Update one GalleryPhoto
   * const galleryPhoto = await prisma.galleryPhoto.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GalleryPhotoUpdateArgs>(args: Prisma.SelectSubset<T, GalleryPhotoUpdateArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GalleryPhotos.
   * @param {GalleryPhotoDeleteManyArgs} args - Arguments to filter GalleryPhotos to delete.
   * @example
   * // Delete a few GalleryPhotos
   * const { count } = await prisma.galleryPhoto.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GalleryPhotoDeleteManyArgs>(args?: Prisma.SelectSubset<T, GalleryPhotoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GalleryPhotos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPhotoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GalleryPhotos
   * const galleryPhoto = await prisma.galleryPhoto.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GalleryPhotoUpdateManyArgs>(args: Prisma.SelectSubset<T, GalleryPhotoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GalleryPhotos and returns the data updated in the database.
   * @param {GalleryPhotoUpdateManyAndReturnArgs} args - Arguments to update many GalleryPhotos.
   * @example
   * // Update many GalleryPhotos
   * const galleryPhoto = await prisma.galleryPhoto.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GalleryPhotos and only return the `id`
   * const galleryPhotoWithIdOnly = await prisma.galleryPhoto.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GalleryPhotoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GalleryPhotoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GalleryPhoto.
   * @param {GalleryPhotoUpsertArgs} args - Arguments to update or create a GalleryPhoto.
   * @example
   * // Update or create a GalleryPhoto
   * const galleryPhoto = await prisma.galleryPhoto.upsert({
   *   create: {
   *     // ... data to create a GalleryPhoto
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GalleryPhoto we want to update
   *   }
   * })
   */
  upsert<T extends GalleryPhotoUpsertArgs>(args: Prisma.SelectSubset<T, GalleryPhotoUpsertArgs<ExtArgs>>): Prisma.Prisma__GalleryPhotoClient<runtime.Types.Result.GetResult<Prisma.$GalleryPhotoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GalleryPhotos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPhotoCountArgs} args - Arguments to filter GalleryPhotos to count.
   * @example
   * // Count the number of GalleryPhotos
   * const count = await prisma.galleryPhoto.count({
   *   where: {
   *     // ... the filter for the GalleryPhotos we want to count
   *   }
   * })
  **/
  count<T extends GalleryPhotoCountArgs>(
    args?: Prisma.Subset<T, GalleryPhotoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GalleryPhotoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GalleryPhoto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPhotoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GalleryPhotoAggregateArgs>(args: Prisma.Subset<T, GalleryPhotoAggregateArgs>): Prisma.PrismaPromise<GetGalleryPhotoAggregateType<T>>

  /**
   * Group by GalleryPhoto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GalleryPhotoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GalleryPhotoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GalleryPhotoGroupByArgs['orderBy'] }
      : { orderBy?: GalleryPhotoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GalleryPhotoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGalleryPhotoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GalleryPhoto model
 */
readonly fields: GalleryPhotoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GalleryPhoto.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GalleryPhotoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  gallery<T extends Prisma.GalleryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GalleryDefaultArgs<ExtArgs>>): Prisma.Prisma__GalleryClient<runtime.Types.Result.GetResult<Prisma.$GalleryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  photo<T extends Prisma.PhotoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PhotoDefaultArgs<ExtArgs>>): Prisma.Prisma__PhotoClient<runtime.Types.Result.GetResult<Prisma.$PhotoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GalleryPhoto model
 */
export interface GalleryPhotoFieldRefs {
  readonly id: Prisma.FieldRef<"GalleryPhoto", 'String'>
  readonly galleryId: Prisma.FieldRef<"GalleryPhoto", 'String'>
  readonly photoId: Prisma.FieldRef<"GalleryPhoto", 'String'>
  readonly order: Prisma.FieldRef<"GalleryPhoto", 'Int'>
  readonly addedAt: Prisma.FieldRef<"GalleryPhoto", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GalleryPhoto findUnique
 */
export type GalleryPhotoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPhoto to fetch.
   */
  where: Prisma.GalleryPhotoWhereUniqueInput
}

/**
 * GalleryPhoto findUniqueOrThrow
 */
export type GalleryPhotoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPhoto to fetch.
   */
  where: Prisma.GalleryPhotoWhereUniqueInput
}

/**
 * GalleryPhoto findFirst
 */
export type GalleryPhotoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPhoto to fetch.
   */
  where?: Prisma.GalleryPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPhotos to fetch.
   */
  orderBy?: Prisma.GalleryPhotoOrderByWithRelationInput | Prisma.GalleryPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GalleryPhotos.
   */
  cursor?: Prisma.GalleryPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPhotos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GalleryPhotos.
   */
  distinct?: Prisma.GalleryPhotoScalarFieldEnum | Prisma.GalleryPhotoScalarFieldEnum[]
}

/**
 * GalleryPhoto findFirstOrThrow
 */
export type GalleryPhotoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPhoto to fetch.
   */
  where?: Prisma.GalleryPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPhotos to fetch.
   */
  orderBy?: Prisma.GalleryPhotoOrderByWithRelationInput | Prisma.GalleryPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GalleryPhotos.
   */
  cursor?: Prisma.GalleryPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPhotos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GalleryPhotos.
   */
  distinct?: Prisma.GalleryPhotoScalarFieldEnum | Prisma.GalleryPhotoScalarFieldEnum[]
}

/**
 * GalleryPhoto findMany
 */
export type GalleryPhotoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * Filter, which GalleryPhotos to fetch.
   */
  where?: Prisma.GalleryPhotoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GalleryPhotos to fetch.
   */
  orderBy?: Prisma.GalleryPhotoOrderByWithRelationInput | Prisma.GalleryPhotoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GalleryPhotos.
   */
  cursor?: Prisma.GalleryPhotoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GalleryPhotos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GalleryPhotos.
   */
  skip?: number
  distinct?: Prisma.GalleryPhotoScalarFieldEnum | Prisma.GalleryPhotoScalarFieldEnum[]
}

/**
 * GalleryPhoto create
 */
export type GalleryPhotoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * The data needed to create a GalleryPhoto.
   */
  data: Prisma.XOR<Prisma.GalleryPhotoCreateInput, Prisma.GalleryPhotoUncheckedCreateInput>
}

/**
 * GalleryPhoto createMany
 */
export type GalleryPhotoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GalleryPhotos.
   */
  data: Prisma.GalleryPhotoCreateManyInput | Prisma.GalleryPhotoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GalleryPhoto createManyAndReturn
 */
export type GalleryPhotoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * The data used to create many GalleryPhotos.
   */
  data: Prisma.GalleryPhotoCreateManyInput | Prisma.GalleryPhotoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GalleryPhoto update
 */
export type GalleryPhotoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * The data needed to update a GalleryPhoto.
   */
  data: Prisma.XOR<Prisma.GalleryPhotoUpdateInput, Prisma.GalleryPhotoUncheckedUpdateInput>
  /**
   * Choose, which GalleryPhoto to update.
   */
  where: Prisma.GalleryPhotoWhereUniqueInput
}

/**
 * GalleryPhoto updateMany
 */
export type GalleryPhotoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GalleryPhotos.
   */
  data: Prisma.XOR<Prisma.GalleryPhotoUpdateManyMutationInput, Prisma.GalleryPhotoUncheckedUpdateManyInput>
  /**
   * Filter which GalleryPhotos to update
   */
  where?: Prisma.GalleryPhotoWhereInput
  /**
   * Limit how many GalleryPhotos to update.
   */
  limit?: number
}

/**
 * GalleryPhoto updateManyAndReturn
 */
export type GalleryPhotoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * The data used to update GalleryPhotos.
   */
  data: Prisma.XOR<Prisma.GalleryPhotoUpdateManyMutationInput, Prisma.GalleryPhotoUncheckedUpdateManyInput>
  /**
   * Filter which GalleryPhotos to update
   */
  where?: Prisma.GalleryPhotoWhereInput
  /**
   * Limit how many GalleryPhotos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GalleryPhoto upsert
 */
export type GalleryPhotoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * The filter to search for the GalleryPhoto to update in case it exists.
   */
  where: Prisma.GalleryPhotoWhereUniqueInput
  /**
   * In case the GalleryPhoto found by the `where` argument doesn't exist, create a new GalleryPhoto with this data.
   */
  create: Prisma.XOR<Prisma.GalleryPhotoCreateInput, Prisma.GalleryPhotoUncheckedCreateInput>
  /**
   * In case the GalleryPhoto was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GalleryPhotoUpdateInput, Prisma.GalleryPhotoUncheckedUpdateInput>
}

/**
 * GalleryPhoto delete
 */
export type GalleryPhotoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
  /**
   * Filter which GalleryPhoto to delete.
   */
  where: Prisma.GalleryPhotoWhereUniqueInput
}

/**
 * GalleryPhoto deleteMany
 */
export type GalleryPhotoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GalleryPhotos to delete
   */
  where?: Prisma.GalleryPhotoWhereInput
  /**
   * Limit how many GalleryPhotos to delete.
   */
  limit?: number
}

/**
 * GalleryPhoto without action
 */
export type GalleryPhotoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryPhoto
   */
  select?: Prisma.GalleryPhotoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryPhoto
   */
  omit?: Prisma.GalleryPhotoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryPhotoInclude<ExtArgs> | null
}
