import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/signup", "routes/auth.signup.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("api/auth/create-user", "routes/api.auth.create-user.tsx"),
  route("api/artwork/upload", "routes/api.artwork.upload.tsx"),
  route("api/user/upload-avatar", "routes/api.user.upload-avatar.tsx"),
  route("api/artworks/search", "routes/api.artworks.search.tsx"),
  route("api/artworks/check-location", "routes/api.artworks.check-location.tsx"),
  route("api/admin/delete-artwork", "routes/api.admin.delete-artwork.tsx"),
  route("api/artwork/add-to-wall", "routes/api.artwork.add-to-wall.tsx"),
  route("api/user/walls", "routes/api.user.walls.tsx"),
  route("api/map/hotspots", "routes/api.map.hotspots.tsx"),
  route("api/browse/countries", "routes/api.browse.countries.tsx"),
  route("api/browse/artists", "routes/api.browse.artists.tsx"),
  route("api/browse/years", "routes/api.browse.years.tsx"),
  route("artwork/register", "routes/artwork.register.tsx"),
  route("artwork/upload", "routes/artwork.upload.tsx"),
  route("artwork/:id", "routes/artwork.$id.tsx"),
  route("uploads/:filename", "routes/uploads.$filename.tsx"),
  route("user/profile", "routes/user.profile.tsx"),
  route("user/settings", "routes/user.settings.tsx"),
  route("user/:id", "routes/user.$id.tsx"),
  route("admin/dashboard", "routes/admin.dashboard.tsx"),
  route("collection/new", "routes/collection.new.tsx"),
  route("collection/:id", "routes/collection.$id.tsx"),
  route("collection/:id/edit", "routes/collection.$id.edit.tsx"),
  route("artists", "routes/artists.tsx"),
  route("artists/:letter", "routes/artists.$letter.tsx"),
  route("artist/:artistId", "routes/artist.$artistId.tsx"),
  route("countries", "routes/countries.tsx"),
  route("countries/:id", "routes/countries.$id.tsx"),
  route("years", "routes/years.tsx"),
  route("years/:year", "routes/years.$year.tsx"),
  route("map", "routes/map.tsx"),
  route("test/header", "routes/test.header.tsx"),
] satisfies RouteConfig;
