
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ARTIST: 'ARTIST',
  REGULAR_USER: 'REGULAR_USER',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const ClaimStatus = {
  UNCLAIMED: 'UNCLAIMED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  CLAIMED: 'CLAIMED'
} as const

export type ClaimStatus = (typeof ClaimStatus)[keyof typeof ClaimStatus]


export const GalleryType = {
  DEFAULT: 'DEFAULT',
  OFFICIAL: 'OFFICIAL'
} as const

export type GalleryType = (typeof GalleryType)[keyof typeof GalleryType]
